// Auto-generated by GitHub Actions — do not edit manually
const firebaseConfig = {
  apiKey:            "AIzaSyCmFNVryw61RPRmWKZy4ZHh4hBdMLH32mk",
  authDomain:        "leads-9be20.firebaseapp.com",
  projectId:         "leads-9be20",
  storageBucket:     "leads-9be20.firebasestorage.app",
  messagingSenderId: "527553398640",
  appId:             "1:527553398640:web:e9ef8a0f713e795f5431b5",
};
firebase.initializeApp(firebaseConfig);
