// Auto-generated by GitHub Actions — do not edit manually
const firebaseConfig = {
  apiKey:            "",
  authDomain:        "",
  projectId:         "",
  storageBucket:     "",
  messagingSenderId: "",
  appId:             "",
};
firebase.initializeApp(firebaseConfig);
